
spring:
  output:
    ansi:
      enabled: ALWAYS

      # Configurações do banco de dados MySQL
      spring:
        datasource:
          url: jdbc:mysql://localhost:3306/seu_banco_de_dados
          username: root
          password: A25042020#
          driver-class-name: com.mysql.cj.jdbc.Driver
        jpa:
          database-platform: org.hibernate.dialect.MySQLDialect
